# requires each day to have the same number of exercises
day-1:
- squat
- paused-bench
- romanian-deadlift
- bulgarian-split-squat
- superman-ab-crunchm
day-2:
- bench
- paused-deadlift
- face-pulls
- tricep-pushdowns
day-3:
- deadlift
- safety-squat-bar
- bulgarian-split-squat
- incline-bench-press
- bicep-curls