# requires each day to have the same number of exercises
day-1:
  - squat
  - romanian-deadlift
  - bulgarian-split-squat
  - decline-leg-raises
  - lunges
  - leg-extension
day-2:
  - bench
  - lat-pulldowns
  - assisted-chest-dips
  - push-ups
  - cable-rows
  - chest-fly
day-3:
  - deadlift
  - hip-thrust
  - kneeling-diamond-push-ups
  - side-raises-front-raises
  - tricep-extensions
  - plank
