squat:
  weight: 40
  reps: 6
  rpe: 9.5
  program_goal: volume-3
bench:
  weight: 25
  reps: 3
  rpe: 9.5
  program_goal: volume-3
deadlift:
  weight: 60
  reps: 6
  rpe: 9.5
  program_goal: volume-3
overhead-press:
  weight: 10
  reps: 6
  rpe: 9.0
  program_goal: volume-3
microplates: False
