squat:
  weight: 140
  reps: 2
  rpe: 9.5
  program-goal: strength-3
bench:
  weight: 25
  reps: 9
  rpe: 9.5
  program-goal: volume-3
deadlift:
  weight: 175
  reps: 6
  rpe: 9.5
  program-goal: volume-3
overhead-press:
  weight: 10
  reps: 6
  rpe: 9.0
  program-goal: volume-3
