squat:
  weight: 40
  reps: 5
  rpe: 9.5
  program-goal: strength-2
bench:
  weight: 25
  reps: 9
  rpe: 9.5
  program-goal: volume-3
deadlift:
  weight: 60
  reps: 6
  rpe: 9.5
  program-goal: volume-3
overhead-press:
  weight: 10
  reps: 6
  rpe: 9.0
  program-goal: volume-3
